[project]
name = "01-agentic-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitsource>=0.0.5",
    "minsearch>=0.1.1",
    "openai>=2.44.0",
    "toyaikit>=0.0.11",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
